### ISSUE TITLE
Questions about the construction of ModelNet10-SO(3) dataset

### ISSUE THREAD

**Issue by yd-yin** [leoshine/Spherical_Regression#10]
Hi, thanks a lot for your great work and useful dataset!

Could you elaborate a bit more about the construction of the ModelNet10-SO(3) dataset? since I may want to reconstruct and re-render the images 

For example, what are the intrinsic and extrinsic parameters of the camera?
Is the original shape in ModelNet10 the reference "canonical" pose (i.e., identity rotation)?

Looking forward to your response
Thanks!

**Comment by yd-yin** [comment]
Hi,
Thanks for your quick response and informative message!

I finally found that maybe it will be more convenient to render by myself:)

Thanks!

**Comment by yd-yin** [comment]
Well, sorry for the bother, but I got another problem...

I tried to render 3D models from ModelNet10 dataset by trimesh + pyrender, but just to find the renderings of some models are incorrect. 

I'm not sure if it is caused by wrong face normals. Did you meet the same issue before?

Thanks a lot!

![b360a44117afe479329cefe759e7b5e](https://user-images.githubusercontent.com/37136395/131224943-fb5ce53a-4df0-4185-8f3f-62332c78bb6e.png)

**Comment by leoshine** [comment]
Indeed. It can be the wrong surface normal or wrong winding of the three vertices of a face (if Trimesh generates the surface normal automatically). I ended up generating the surface from the triangle face definition myself, instead of using any surface normal defined in the CAD file. This at least corrects the back-facing problem, however, the rendered surface may not be that smooth.
